### ISSUE TITLE
Crear scripts de javascript por separado

### ISSUE THREAD

**Issue by asmateus** [juliansibaja84/GPStracking#2]
Por alguna razón cuando se ejecuta la aplicación usando UWSGI, Django no es capaz de encontrar la ruta a los archivos de javascript. Solucionar esto; puede ser útil hacer las siguientes búsquedas:
- static files in django
  Depronto sea necesario correr un `collectstatic`, no sé.

**Comment by juliansibaja84** [comment]
Arreglado!
