### ISSUE TITLE
Actualizar el código de Frontend

### ISSUE THREAD

**Issue by asmateus** [juliansibaja84/GPStracking#3]
El servidor ahora manda un tipo diferente de información, un diccionario de `strings`, como el siguiente:

`dictio = {ips="ips1;ips2", prt="prt1;prt2", lat="lat1;lat2",lon="lon1;lon2",tmp="tmp1,tmp2" }`,

donde se encuentra toda la información de la base de datos. La idea es actualizar el javascript para que circule los datos y ponga los puntos respectivos en el mapa.

**Comment by juliansibaja84** [comment]
all clear!
