### ISSUE TITLE
Usar dos tipos de fetch de datos

### ISSUE THREAD

**Issue by asmateus** [juliansibaja84/GPStracking#4]
El servidor puede entregar dos tipos de datos, un json con todos los elementos de la base de datos y un json con únicamente el último registro, la información se obtiene haciendo la petición a las siguientes URLS respectivamente:

`/finder/req/all` y

`finder/req/one`,

el primer tipo de petición debe realizarse cuando se carga inicialmente la página, el segundo tipo es el que se ejecuta continuamente (cada 2 segundos). Hacer esto.

**Comment by asmateus** [comment]
Mira el código de views para que entiendas mejor.

**Comment by juliansibaja84** [comment]
all clear!
